// Main test runner for ChipNomad unified test executable
// This file contains the doctest main() implementation
// All other test files just include doctest.h without DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest.h"

// The main() function is automatically generated by doctest
// Run with --help to see all available command-line options
