baseURL = 'https://chipnomad.org/'
locale = 'en-us'
title = 'ChipNomad'

enableEmoji = true

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      wrapStandaloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true

[params]
  description = 'ChipNomad - a chiptune tracker for handheld consoles'
  title = 'ChipNomad'
  images = ['site-cover.jpg']

[menu]
[[menu.main]]
  name = 'Download'
  url = 'https://github.com/Megus/chipnomad-tracker/releases'
  weight = 10
[[menu.main]]
  name = 'Manual'
  pageRef = '/manual/'
  weight = 20
[[menu.main]]
  name = 'Promo Album'
  pageRef = '/promo-album/'
  weight = 30
[[menu.main]]
  name = 'Discord'
  url = 'https://discord.gg/PJarAn2QCW'
  weight = 40
[[menu.main]]
  name = 'GitHub'
  url = 'https://github.com/Megus/chipnomad-tracker'
  weight = 50