#ifndef __CHIPNOMAD_LIB__PROJECT_CONSTANTS_H__
#define __CHIPNOMAD_LIB__PROJECT_CONSTANTS_H__

#define PROJECT_MAX_TRACKS (10)
#define PROJECT_MAX_LENGTH (256)
#define PROJECT_MAX_CHAINS (255)
#define PROJECT_MAX_PHRASES (1024)
#define PROJECT_MAX_GROOVES (32)
#define PROJECT_MAX_INSTRUMENTS (128)
#define PROJECT_MAX_TABLES (255)
#define PROJECT_MAX_CHIPS (3)
#define PROJECT_MAX_PITCHES (254)
#define PROJECT_MAX_SAMPLE_SIZE (16384)
#define PROJECT_INSTRUMENT_NAME_LENGTH (15)
#define PROJECT_TITLE_LENGTH (24)
#define PROJECT_PITCH_TABLE_TITLE_LENGTH (18)

#define NOTE_OFF (254)
#define EMPTY_VALUE_8 (255)
#define EMPTY_VALUE_16 (32767)

#endif // __CHIPNOMAD_LIB__PROJECT_CONSTANTS_H__
