# Native ARM64 PortMaster build from Ubuntu/WSL2.

PLATFORM = portmaster
include Makefile.common

LIBS = $(COMMON_LIBS) platforms/sdl2
CXX = aarch64-linux-gnu-g++
STRIP = aarch64-linux-gnu-strip
PKG_CONFIG ?= pkg-config
PKG_CONFIG_LIBDIR ?= /usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig

SDL_CFLAGS = $(shell PKG_CONFIG_LIBDIR=$(PKG_CONFIG_LIBDIR) $(PKG_CONFIG) --cflags sdl2)
SDL_LIBS = $(shell PKG_CONFIG_LIBDIR=$(PKG_CONFIG_LIBDIR) $(PKG_CONFIG) --libs sdl2)
CFLAGS = $(COMMON_CFLAGS) $(INCLUDES) $(SOURCES) $(SDL_CFLAGS) -DPORTMASTER_BUILD -DGAMEPAD_SUPPORT
OUTPUT = -o $(BUILD)/mobilegroove.aarch64

PACKAGE_ROOT = $(BUILD)/package
PORT_DIR = $(PACKAGE_ROOT)/mobilegroove
RELEASE = ../releases/mobilegroove.zip

.PHONY: PortMaster
PortMaster: $(BUILD)/mobilegroove.aarch64

$(BUILD)/mobilegroove.aarch64: $(SRC_FILES) Makefile.portmaster Makefile.common
	mkdir -p $(BUILD)
	$(CXX) $(CFLAGS) $(SDL_LIBS) -lm $(OUTPUT)
	$(STRIP) $(BUILD)/mobilegroove.aarch64

.PHONY: PortMaster-deploy
PortMaster-deploy: PortMaster
	mkdir -p $(PORT_DIR)/licenses ../releases
	cp $(BUILD)/mobilegroove.aarch64 $(PORT_DIR)/
	cp packaging/portmaster/mobilegroove.gptk $(PORT_DIR)/
	cp -r packaging/common/. $(PORT_DIR)/
	cp ../LICENSE $(PORT_DIR)/licenses/LICENSE.mobile-groove.md
	cp packaging/portmaster/license/* $(PORT_DIR)/licenses/
	cp packaging/portmaster/MobileGroove.sh $(PACKAGE_ROOT)/
	cp packaging/portmaster/port.json packaging/portmaster/README.md packaging/portmaster/gameinfo.xml packaging/portmaster/cover.png packaging/portmaster/screenshot.png $(PACKAGE_ROOT)/
	chmod +x $(PACKAGE_ROOT)/MobileGroove.sh $(PORT_DIR)/mobilegroove.aarch64
	sed -i "s/BUILD_DATE_PLACEHOLDER/$$(date +%Y%m%dT%H%M%S)/" $(PACKAGE_ROOT)/gameinfo.xml
	rm -f $(BUILD)/mobilegroove.zip $(RELEASE)
	cd $(PACKAGE_ROOT) && zip -qr ../mobilegroove.zip .
	cp $(BUILD)/mobilegroove.zip $(RELEASE)
	@echo "PortMaster package created: $(RELEASE)"
