# Native ARM64 PortMaster build from Ubuntu/WSL2.

PLATFORM = portmaster
include Makefile.common

LIBS = $(COMMON_LIBS) platforms/sdl2
CXX = aarch64-linux-gnu-g++
STRIP = aarch64-linux-gnu-strip
PKG_CONFIG ?= pkg-config
PKG_CONFIG_SYSROOT_DIR ?=
ifeq ($(strip $(PKG_CONFIG_LIBDIR)),)
PKG_CONFIG_LIBDIR = $(if $(PKG_CONFIG_SYSROOT_DIR),$(PKG_CONFIG_SYSROOT_DIR)/usr/lib/aarch64-linux-gnu/pkgconfig:$(PKG_CONFIG_SYSROOT_DIR)/usr/share/pkgconfig,/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig)
endif

ifneq ($(strip $(PKG_CONFIG_SYSROOT_DIR)),)
SDL_CFLAGS := -I$(PKG_CONFIG_SYSROOT_DIR)/usr/include -I$(PKG_CONFIG_SYSROOT_DIR)/usr/include/aarch64-linux-gnu
SDL_LIBS := -L$(PKG_CONFIG_SYSROOT_DIR)/usr/lib/aarch64-linux-gnu -lSDL2 -Wl,--allow-shlib-undefined
else
SDL_CFLAGS := $(shell PKG_CONFIG_LIBDIR=$(PKG_CONFIG_LIBDIR) $(PKG_CONFIG) --cflags sdl2)
SDL_LIBS := $(shell PKG_CONFIG_LIBDIR=$(PKG_CONFIG_LIBDIR) $(PKG_CONFIG) --libs sdl2)
endif
CFLAGS = $(COMMON_CFLAGS) $(INCLUDES) $(SDL_CFLAGS) -DPORTMASTER_BUILD -DGAMEPAD_SUPPORT
TARGET = $(BUILD)/choochootracker.aarch64
OUTPUT = -o $(TARGET)

object_for = $(BUILD)/obj/$(subst ../,up/,$(basename $(1))).o
OBJECTS := $(foreach source,$(SOURCES),$(call object_for,$(source)))
DEPS := $(OBJECTS:.o=.d)

define compile_source
$(call object_for,$(1)): $(1) Makefile.portmaster Makefile.common
	@mkdir -p $$(dir $$@)
	@$(CXX) $(CFLAGS) -MMD -MP -c $$< -o $$@
endef

$(foreach source,$(SOURCES),$(eval $(call compile_source,$(source))))
-include $(DEPS)

PACKAGE_ROOT = $(BUILD)/package
PORT_DIR = $(PACKAGE_ROOT)/choochootracker
RELEASE = ../releases/choochootracker.zip

.PHONY: PortMaster
PortMaster: $(BUILD)/choochootracker.aarch64

$(BUILD)/choochootracker.aarch64: $(OBJECTS)
	mkdir -p $(BUILD)
	$(CXX) $(COMMON_CFLAGS) $(OBJECTS) $(SDL_LIBS) -lm $(OUTPUT)
	$(STRIP) $(BUILD)/choochootracker.aarch64

.PHONY: PortMaster-deploy
PortMaster-deploy: PortMaster
	rm -rf $(PACKAGE_ROOT)
	mkdir -p $(PORT_DIR)/licenses ../releases
	cp $(BUILD)/choochootracker.aarch64 $(PORT_DIR)/
	cp packaging/portmaster/choochootracker.gptk $(PORT_DIR)/
	cp -r packaging/common/. $(PORT_DIR)/
	cp ../docs/USER_MANUAL.md $(PORT_DIR)/
	cp ../LICENSE $(PORT_DIR)/licenses/LICENSE.choochootracker.md
	cp packaging/portmaster/license/* $(PORT_DIR)/licenses/
	cp packaging/portmaster/ChooChooTracker.sh $(PACKAGE_ROOT)/
	cp packaging/portmaster/port.json packaging/portmaster/README.md packaging/portmaster/gameinfo.xml packaging/portmaster/cover.png packaging/portmaster/screenshot.png $(PORT_DIR)/
	chmod +x $(PACKAGE_ROOT)/ChooChooTracker.sh $(PORT_DIR)/choochootracker.aarch64
	sed -i "s/BUILD_DATE_PLACEHOLDER/$$(date +%Y%m%dT%H%M%S)/" $(PORT_DIR)/gameinfo.xml
	rm -f $(BUILD)/choochootracker.zip $(RELEASE)
	cd $(PACKAGE_ROOT) && zip -qr ../choochootracker.zip .
	cp $(BUILD)/choochootracker.zip $(RELEASE)
	@echo "PortMaster package created: $(RELEASE)"
